export { analyzeDependencies } from './core/analysis.js'
export { generateFixes, applyFixes } from './core/fixes.js'
export { detectFunctionalOverlap } from './core/detection/functional-overlap.js'
export { detectBuiltInReplacements } from './core/detection/built-in-replacements.js'
export { detectHallucinations, checkPackageExists, checkSuspiciousPatterns, checkPotentialTypos, levenshteinDistance } from './core/detection/hallucinations.js'
export { formatResults, formatJsonOutput, generateSummaryReport } from './utils/formatter.js'
export { loadPackageJson, validatePackageJson } from './utils/package-loader.js'
export { DependencyUtils } from './utils/dependency-utils.js'
export type { PackageJson, LockFile } from './types/package-json.js'
export type { AnalysisConfig, AnalysisResult, DetectionResult } from './types/analysis.js'
export type { DependencyIssue, DependencySuggestion, DependencyWarning, IssueSeverity, DependencyImpact, SuggestionAction } from './types/dependency-issues.js'
